package:
  name: dlib
  version: "18.18"

source:
  fn: dlib-18.18.tar.bz2
  url: http://sourceforge.net/projects/dclib/files/dlib/v18.18/dlib-18.18.tar.bz2/download
  sha1: 21421b55e22387dfa428a221653172bf740b55ed
  
  patches:
    - cmake_static_boost.patch  # [win]

build:
  number: 0

requirements:
  build:
   - python
   - cmake
   - boost 1.56.*
   # On OSX Davis has forced building the static version
   # On Windows there is a conflict between this jpeg and windows.h
   - jpeg 8d  # [linux]
   - libpng 1.6.17
   - sqlite 3.8.4.1  # [unix]

  run:
   - python
   - boost 1.56.*
   - jpeg 8d  # [linux]
   - libpng 1.6.17
   - sqlite 3.8.4.1  # [unix]

test:
  requires:
    - numpy
    - pillow

  imports:
    - dlib

about:
  home: http://dlib.net/
  license: Boost Software License
